### ISSUE TITLE
.gitmodules file on master branch is out-of-date

### ISSUE THREAD

**Issue by allisterb** [snipsco/snips-nlu-rs#12]
https://github.com/snipsco/snips-nlu-rs/blob/master/.gitmodules has 
```
[submodule "snips-nlu-resources/snips-nlu-resources"]
	path = snips-nlu-resources/snips-nlu-resources
url = ssh://git@github.com/snipsco/snips-nlu-resources
```
The url should use https and not ssh otherwise Cargo can't fetch it for anonymous users. The .gitmodules on the develop branch has the correct url but the instructions in README.rst say to use the master branch with Cargo. 

> Installation
> 
> Add it to your Cargo.toml:
> 
> [dependencies]
> snips-nlu-lib = { git = "https://github.com/snipsco/snips-nlu-rs", branch = "master" }

You might want to commit the updated version to master or change the instructions to say to use the develop branch. Using the develop branch in Cargo I was able to build the project.

**Comment by klefevre** [comment]
Sorry for the mistake, `develop` was indeed up-to-date but not `master`. I just released a new version and merged everything into master. Everything should be ok now. Thanks.
