### ISSUE TITLE
Can one engine instance be used across mnany threads?

### ISSUE THREAD

**Issue by allisterb** [snipsco/snips-nlu-rs#154]
I want to use the native snips_nlu_ffi library binary in a multi-threaded app. Is it safe to share one engine pointer across many threads and call functions like `snips_nlu_engine_run_get_intents` concurrently?

**Comment by fredszaq** [comment]
@allisterb the engine is internally protected by a mutex, so you can share it across threads and use it concurently without any problems

**Comment by adrienball** [comment]
@fredszaq The underlying `SnipsNluEngine` is `Send + Sync` so I think we could get rid of this mutex (there are other mutexes at a lower level in the implementation).
This would improve concurrency.

**Comment by allisterb** [comment]
Awesome, thanks a lot.
