### ISSUE TITLE
Many intents

### ISSUE THREAD

**Issue by Nainterceptor** [snipsco/snips-nlu-rs#69]
Hello,

I'm looking for an NLU engine for a chatbot project. Firstly, thanks for opensourcing this rust lib !

One sentence seems to be linked to only one intent, is it a kind of limitation, isn't it ?

As an example : "Can you open the door and put light on ?".
Here I've two intents : DoorOpening and PutLightsOn.

Any way to achieve this one ? 

Maybe it's easy for Deterministic intent parser but not for probabilistic one, maybe returning all intents with probability and let the app pick one or many (as an example, a strategy may be to take all intents with probability over 90% ?)

Thanks,
Gaël

**Comment by adrienball** [comment]
Hello @Nainterceptor ,
Handling multiple intents is definitely in our mid-term roadmap, see [this thread](https://github.com/snipsco/snips-nlu/issues/623) on the `snips-nlu` python repo.
There are actually two features around multiple intents:
- Handle sentences which contain multiple intents (this is your example)
- Add an API to get not only the most likely intent, but rather the top `n` intents. In this case, the input may be about only one (ambiguous) intent.

These two features may turn out to be interconnected, depending on how we decide to move forward.
The ETA for this is around October.

Thanks,
Adrien

**Comment by Nainterceptor** [comment]
Hello, thanks for your answer, I'm subscribing to mentioned thread. I'm losing this one so.

Thanks again for your job 👍

**Comment by anand-srinivasan** [comment]
@adrienball - Looks like "Add new parsing apis #724" have been already merged - Any plans to support the same on rust as well? 

Thanks,
Anand

**Comment by adrienball** [comment]
@anand-srinivasan 
This has already been done in https://github.com/snipsco/snips-nlu-rs/pull/107

**Comment by anand-srinivasan** [comment]
@adrienball - Thank You 👍 Are there any plans to include slots as part of all top_n intents in near future or something like adding top_n candidate to Parse method ! Please correct me if i am wrong.

Thanks,
Anand S
